#CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --dataset_name moeImouto --dataset_path "/edahome/pcslab/pcs05/edwin/data/moeimouto_animefacecharacterdataset/" --batch_size 64 --train_epochs 200 --epoch_decay 50 --image_size 128 --model_type resnet18 --name moeImouto_resnet18_ptFalse_batch64_imageSize128_200epochs_epochDecay50 > moeImouto_resnet18_ptFalse_batch64_imageSize128_200epochs_epochDecay50.txt
#CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --dataset_name moeImouto --dataset_path "/edahome/pcslab/pcs05/edwin/data/moeimouto_animefacecharacterdataset/" --batch_size 64 --train_epochs 200 --epoch_decay 50 --image_size 128 --model_type resnet18 --pretrained True --name moeImouto_resnet18_ptTrue_batch64_imageSize128_200epochs_epochDecay50 > moeImouto_resnet18_ptTrue_batch64_imageSize128_200epochs_epochDecay50.txt

#CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --dataset_name moeImouto --dataset_path "/edahome/pcslab/pcs05/edwin/data/moeimouto_animefacecharacterdataset/" --batch_size 64 --train_epochs 200 --epoch_decay 50 --image_size 128 --model_type resnet152 --name moeImouto_resnet152_ptFalse_batch64_imageSize128_200epochs_epochDecay50 > moeImouto_resnet152_ptFalse_batch64_imageSize128_200epochs_epochDecay50.txt
#CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --dataset_name moeImouto --dataset_path "/edahome/pcslab/pcs05/edwin/data/moeimouto_animefacecharacterdataset/" --batch_size 64 --train_epochs 200 --epoch_decay 50 --image_size 128 --model_type resnet152 --pretrained True --name moeImouto_resnet152_ptTrue_batch64_imageSize128_200epochs_epochDecay50 > moeImouto_resnet152_ptTrue_batch64_imageSize128_200epochs_epochDecay50.txt

#CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --dataset_name moeImouto --dataset_path "/edahome/pcslab/pcs05/edwin/data/moeimouto_animefacecharacterdataset/" --batch_size 64 --train_epochs 200 --epoch_decay 50 --image_size 128 --model_type B_16 --name moeImouto_b16_ptFalse_batch64_imageSize128_200epochs_epochDecay50 > moeImouto_b16_ptFalse_batch64_imageSize128_200epochs_epochDecay50.txt
#CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --dataset_name moeImouto --dataset_path "/edahome/pcslab/pcs05/edwin/data/moeimouto_animefacecharacterdataset/" --batch_size 64 --train_epochs 200 --epoch_decay 50 --image_size 128 --model_type B_16 --pretrained True --name moeImouto_b16_ptTrue_batch64_imageSize128_200epochs_epochDecay50 > moeImouto_b16_ptTrue_batch64_imageSize128_200epochs_epochDecay50.txt

#CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --dataset_name moeImouto --dataset_path "/edahome/pcslab/pcs05/edwin/data/moeimouto_animefacecharacterdataset/" --batch_size 64 --train_epochs 200 --epoch_decay 50 --image_size 128 --model_type B_32 --name moeImouto_b32_ptFalse_batch64_imageSize128_200epochs_epochDecay50 > moeImouto_b32_ptFalse_batch64_imageSize128_200epochs_epochDecay50.txt
#CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --dataset_name moeImouto --dataset_path "/edahome/pcslab/pcs05/edwin/data/moeimouto_animefacecharacterdataset/" --batch_size 64 --train_epochs 200 --epoch_decay 50 --image_size 128 --model_type B_32 --pretrained True --name moeImouto_b32_ptTrue_batch64_imageSize128_200epochs_epochDecay50 > moeImouto_b32_ptTrue_batch64_imageSize128_200epochs_epochDecay50.txt

#CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --dataset_name moeImouto --dataset_path "/edahome/pcslab/pcs05/edwin/data/moeimouto_animefacecharacterdataset/" --batch_size 64 --train_epochs 200 --epoch_decay 50 --image_size 128 --model_type L_16 --name moeImouto_l16_ptFalse_batch64_imageSize128_200epochs_epochDecay50 > moeImouto_l16_ptFalse_batch64_imageSize128_200epochs_epochDecay50.txt
#CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --dataset_name moeImouto --dataset_path "/edahome/pcslab/pcs05/edwin/data/moeimouto_animefacecharacterdataset/" --batch_size 64 --train_epochs 200 --epoch_decay 50 --image_size 128 --model_type L_16 --pretrained True --name moeImouto_l16_ptTrue_batch64_imageSize128_200epochs_epochDecay50 > moeImouto_l16_ptTrue_batch64_imageSize128_200epochs_epochDecay50.txt

#CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --dataset_name moeImouto --dataset_path "/edahome/pcslab/pcs05/edwin/data/moeimouto_animefacecharacterdataset/" --batch_size 64 --train_epochs 200 --epoch_decay 50 --image_size 128 --model_type L_32 --name moeImouto_l32_ptFalse_batch64_imageSize128_200epochs_epochDecay50 > moeImouto_l32_ptFalse_batch64_imageSize128_200epochs_epochDecay50.txt
#CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --dataset_name moeImouto --dataset_path "/edahome/pcslab/pcs05/edwin/data/moeimouto_animefacecharacterdataset/" --batch_size 64 --train_epochs 200 --epoch_decay 50 --image_size 128 --model_type L_32 --pretrained True --name moeImouto_l32_ptTrue_batch64_imageSize128_200epochs_epochDecay50 > moeImouto_l32_ptTrue_batch64_imageSize128_200epochs_epochDecay50.txt

#CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --name danbooruFaces_l16_ptFalse_batch64_imageSize128_50epochs_epochDecay20 --dataset_name danbooruFaces --dataset_path "/edahome/pcslab/pcs05/edwin/data/Danbooru2018AnimeCharacterRecognitionDataset_Revamped/" --train_epochs 50 --epoch_decay 20 --batch_size 64 --model_type L_16 --image_size 128 > danbooruFaces_l16_ptFalse_batch64_imageSize128_50epochs_epochDecay20.txt
#CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --name danbooruFaces_l16_ptTrue_batch64_imageSize128_50epochs_epochDecay20 --dataset_name danbooruFaces --dataset_path "/edahome/pcslab/pcs05/edwin/data/Danbooru2018AnimeCharacterRecognitionDataset_Revamped/" --train_epochs 50 --epoch_decay 20 --batch_size 64 --model_type L_16 --image_size 128 --pretrained True > danbooruFaces_l16_ptTrue_batch64_imageSize128_50epochs_epochDecay20.txt

CUDA_VISIBLE_DEVICES=1 nohup python -u train.py --name danbooruFaces_l16_ptTrue_batch128_imageSize128_50epochs_epochDecay20 --dataset_name danbooruFaces --dataset_path "/edahome/pcslab/pcs05/edwin/data/Danbooru2018AnimeCharacterRecognitionDataset_Revamped/" --train_epochs 50 --epoch_decay 20 --batch_size 128 --model_type L_16 --image_size 128 --pretrained True > danbooruFaces_l16_ptTrue_batch128_imageSize128_50epochs_epochDecay20.txt

CUDA_VISIBLE_DEVICES=1 nohup python -u train.py --name danbooruFaces_l32_ptTrue_batch256_imageSize128_50epochs_epochDecay20 --dataset_name danbooruFaces --dataset_path "/edahome/pcslab/pcs05/edwin/data/Danbooru2018AnimeCharacterRecognitionDataset_Revamped/" --train_epochs 50 --epoch_decay 20 --batch_size 256 --model_type L_32 --image_size 128 --pretrained True > danbooruFaces_l32_ptTrue_batch256_imageSize128_50epochs_epochDecay20.txt
CUDA_VISIBLE_DEVICES=1 nohup python -u train.py --name danbooruFaces_l32_ptTrue_batch128_imageSize128_50epochs_epochDecay20 --dataset_name danbooruFaces --dataset_path "/edahome/pcslab/pcs05/edwin/data/Danbooru2018AnimeCharacterRecognitionDataset_Revamped/" --train_epochs 50 --epoch_decay 20 --batch_size 128 --model_type L_32 --image_size 128 --pretrained True > danbooruFaces_l32_ptTrue_batch128_imageSize128_50epochs_epochDecay20.txt

CUDA_VISIBLE_DEVICES=1 nohup python -u train.py --name danbooruFaces_b32_ptTrue_batch256_imageSize128_50epochs_epochDecay20 --dataset_name danbooruFaces --dataset_path "/edahome/pcslab/pcs05/edwin/data/Danbooru2018AnimeCharacterRecognitionDataset_Revamped/" --train_epochs 50 --epoch_decay 20 --batch_size 256 --model_type B_32 --image_size 128 --pretrained True > danbooruFaces_b32_ptTrue_batch256_imageSize128_50epochs_epochDecay20.txt
CUDA_VISIBLE_DEVICES=1 nohup python -u train.py --name danbooruFaces_b32_ptTrue_batch128_imageSize128_50epochs_epochDecay20 --dataset_name danbooruFaces --dataset_path "/edahome/pcslab/pcs05/edwin/data/Danbooru2018AnimeCharacterRecognitionDataset_Revamped/" --train_epochs 50 --epoch_decay 20 --batch_size 128 --model_type B_32 --image_size 128 --pretrained True > danbooruFaces_b32_ptTrue_batch128_imageSize128_50epochs_epochDecay20.txt

CUDA_VISIBLE_DEVICES=1 nohup python -u train.py --name danbooruFaces_b16_ptTrue_batch256_imageSize128_50epochs_epochDecay20 --dataset_name danbooruFaces --dataset_path "/edahome/pcslab/pcs05/edwin/data/Danbooru2018AnimeCharacterRecognitionDataset_Revamped/" --train_epochs 50 --epoch_decay 20 --batch_size 256 --model_type B_16 --image_size 128 --pretrained True > danbooruFaces_b16_ptTrue_batch256_imageSize128_50epochs_epochDecay20.txt
CUDA_VISIBLE_DEVICES=1 nohup python -u train.py --name danbooruFaces_b16_ptTrue_batch128_imageSize128_50epochs_epochDecay20 --dataset_name danbooruFaces --dataset_path "/edahome/pcslab/pcs05/edwin/data/Danbooru2018AnimeCharacterRecognitionDataset_Revamped/" --train_epochs 50 --epoch_decay 20 --batch_size 128 --model_type B_16 --image_size 128 --pretrained True > danbooruFaces_b16_ptTrue_batch128_imageSize128_50epochs_epochDecay20.txt

