CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --name danbooruFaces_l16_ptTrue_batch32_imageSize128_50epochs_epochDecay20 --dataset_name danbooruFaces --dataset_path "/edahome/pcslab/pcs05/edwin/data/Danbooru2018AnimeCharacterRecognitionDataset_Revamped/" --train_epochs 50 --epoch_decay 20 --batch_size 32 --model_type L_16 --image_size 128 --pretrained True > danbooruFaces_l16_ptTrue_batch32_imageSize128_50epochs_epochDecay20.txt
CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --name danbooruFaces_l16_ptTrue_batch16_imageSize128_50epochs_epochDecay20 --dataset_name danbooruFaces --dataset_path "/edahome/pcslab/pcs05/edwin/data/Danbooru2018AnimeCharacterRecognitionDataset_Revamped/" --train_epochs 50 --epoch_decay 20 --batch_size 16 --model_type L_16 --image_size 128 --pretrained True > danbooruFaces_l16_ptTrue_batch16_imageSize128_50epochs_epochDecay20.txt

CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --name danbooruFaces_l32_ptTrue_batch32_imageSize128_50epochs_epochDecay20 --dataset_name danbooruFaces --dataset_path "/edahome/pcslab/pcs05/edwin/data/Danbooru2018AnimeCharacterRecognitionDataset_Revamped/" --train_epochs 50 --epoch_decay 20 --batch_size 32 --model_type L_32 --image_size 128 --pretrained True > danbooruFaces_l32_ptTrue_batch32_imageSize128_50epochs_epochDecay20.txt
CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --name danbooruFaces_l32_ptTrue_batch16_imageSize128_50epochs_epochDecay20 --dataset_name danbooruFaces --dataset_path "/edahome/pcslab/pcs05/edwin/data/Danbooru2018AnimeCharacterRecognitionDataset_Revamped/" --train_epochs 50 --epoch_decay 20 --batch_size 16 --model_type L_32 --image_size 128 --pretrained True > danbooruFaces_l32_ptTrue_batch16_imageSize128_50epochs_epochDecay20.txt

CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --name danbooruFaces_b32_ptTrue_batch32_imageSize128_50epochs_epochDecay20 --dataset_name danbooruFaces --dataset_path "/edahome/pcslab/pcs05/edwin/data/Danbooru2018AnimeCharacterRecognitionDataset_Revamped/" --train_epochs 50 --epoch_decay 20 --batch_size 32 --model_type B_32 --image_size 128 --pretrained True > danbooruFaces_b32_ptTrue_batch32_imageSize128_50epochs_epochDecay20.txt
CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --name danbooruFaces_b32_ptTrue_batch16_imageSize128_50epochs_epochDecay20 --dataset_name danbooruFaces --dataset_path "/edahome/pcslab/pcs05/edwin/data/Danbooru2018AnimeCharacterRecognitionDataset_Revamped/" --train_epochs 50 --epoch_decay 20 --batch_size 16 --model_type B_32 --image_size 128 --pretrained True > danbooruFaces_b32_ptTrue_batch16_imageSize128_50epochs_epochDecay20.txt

CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --name danbooruFaces_b16_ptTrue_batch32_imageSize128_50epochs_epochDecay20 --dataset_name danbooruFaces --dataset_path "/edahome/pcslab/pcs05/edwin/data/Danbooru2018AnimeCharacterRecognitionDataset_Revamped/" --train_epochs 50 --epoch_decay 20 --batch_size 32 --model_type B_16 --image_size 128 --pretrained True > danbooruFaces_b16_ptTrue_batch32_imageSize128_50epochs_epochDecay20.txt
CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --name danbooruFaces_b16_ptTrue_batch16_imageSize128_50epochs_epochDecay20 --dataset_name danbooruFaces --dataset_path "/edahome/pcslab/pcs05/edwin/data/Danbooru2018AnimeCharacterRecognitionDataset_Revamped/" --train_epochs 50 --epoch_decay 20 --batch_size 16 --model_type B_16 --image_size 128 --pretrained True > danbooruFaces_b16_ptTrue_batch16_imageSize128_50epochs_epochDecay20.txt

